"""Monthly report generation — creates HTML and CSV summary reports.

Replaces ``generate_report.sh``.  Uses Python string formatting
instead of ``heredoc`` templates.
"""

from __future__ import annotations

import csv
import sys
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any, Optional

from acmecorp_pipeline.config import PipelineConfig, load_config
from acmecorp_pipeline.db_helpers import run_query
from acmecorp_pipeline.logging_utils import get_logger, setup_logging
from acmecorp_pipeline.notifications import send_slack
from acmecorp_pipeline.s3_sync import s3_upload_file

log = get_logger("generate_report")


def _query_rows(config: PipelineConfig, sql: str) -> list[tuple[Any, ...]]:
    """Helper that returns an empty list instead of ``None``."""
    return run_query(config, sql, profile="production") or []


def _generate_summary(config: PipelineConfig, report_month: str) -> dict[str, Any]:
    """Gather summary statistics for *report_month* (``YYYY-MM``)."""
    start_date = f"{report_month}-01"
    # Calculate end date
    year, month = map(int, report_month.split("-"))
    if month == 12:
        end_date = f"{year + 1}-01-01"
    else:
        end_date = f"{year}-{month + 1:02d}-01"

    summary: dict[str, Any] = {
        "month": report_month,
        "generated": datetime.now().isoformat(),
    }

    # Total rows loaded per table
    tables = [
        "raw_ingest.vendor_a_orders",
        "raw_ingest.vendor_b_transactions",
        "raw_ingest.vendor_c_shipments",
        "raw_ingest.customer_data",
        "raw_ingest.product_catalog",
    ]
    table_counts: dict[str, int] = {}
    for table in tables:
        rows = _query_rows(
            config,
            f"SELECT COUNT(*) FROM {table} "
            f"WHERE _load_date >= '{start_date}' AND _load_date < '{end_date}';",
        )
        table_counts[table] = int(rows[0][0]) if rows else 0
    summary["table_counts"] = table_counts
    summary["total_rows"] = sum(table_counts.values())

    # Daily load counts
    rows = _query_rows(
        config,
        f"""SELECT _load_date, COUNT(*)
        FROM raw_ingest.vendor_a_orders
        WHERE _load_date >= '{start_date}' AND _load_date < '{end_date}'
        GROUP BY _load_date ORDER BY _load_date;""",
    )
    summary["daily_loads"] = [(str(r[0]), int(r[1])) for r in rows]

    # Data quality summary
    rows = _query_rows(
        config,
        f"""SELECT COUNT(*) FROM raw_ingest.vendor_a_orders
        WHERE _load_date >= '{start_date}' AND _load_date < '{end_date}'
        AND (order_id IS NULL OR order_id = '');""",
    )
    summary["null_order_ids"] = int(rows[0][0]) if rows else 0

    return summary


def _write_html_report(summary: dict[str, Any], output_file: Path) -> None:
    """Write an HTML report."""
    table_rows = ""
    for table, count in summary.get("table_counts", {}).items():
        short_name = table.split(".")[-1]
        table_rows += f"      <tr><td>{short_name}</td><td>{count:,}</td></tr>\n"

    html = f"""<!DOCTYPE html>
<html>
<head>
  <title>AcmeCorp Pipeline Report - {summary['month']}</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 40px; }}
    h1 {{ color: #333; }}
    table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
    th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
    th {{ background-color: #4CAF50; color: white; }}
    tr:nth-child(even) {{ background-color: #f2f2f2; }}
    .summary {{ background: #f9f9f9; padding: 20px; border-radius: 5px; margin: 20px 0; }}
  </style>
</head>
<body>
  <h1>AcmeCorp Data Pipeline — Monthly Report</h1>
  <div class="summary">
    <p><strong>Report Month:</strong> {summary['month']}</p>
    <p><strong>Generated:</strong> {summary['generated']}</p>
    <p><strong>Total Rows Loaded:</strong> {summary.get('total_rows', 0):,}</p>
  </div>

  <h2>Rows Loaded by Table</h2>
  <table>
    <tr><th>Table</th><th>Row Count</th></tr>
{table_rows}  </table>

  <h2>Data Quality</h2>
  <ul>
    <li>Null Order IDs: {summary.get('null_order_ids', 0):,}</li>
  </ul>

  <p><em>Report generated by AcmeCorp Data Pipeline v2.0 (Python)</em></p>
</body>
</html>"""

    output_file.write_text(html)
    log.info("HTML report written: %s", output_file)


def _write_csv_report(summary: dict[str, Any], output_file: Path) -> None:
    """Write a CSV summary."""
    with open(output_file, "w", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["table", "row_count"])
        for table, count in summary.get("table_counts", {}).items():
            writer.writerow([table, count])
    log.info("CSV report written: %s", output_file)


def generate_report(
    config: PipelineConfig,
    report_month: Optional[str] = None,
) -> bool:
    """Generate the monthly pipeline report.

    Args:
        config: Pipeline configuration.
        report_month: Month in ``YYYY-MM`` format; defaults to previous month.

    Returns:
        ``True`` on success.
    """
    if report_month is None:
        today = date.today()
        first_of_month = today.replace(day=1)
        prev_month = first_of_month - timedelta(days=1)
        report_month = prev_month.strftime("%Y-%m")

    log.info("Generating report for %s", report_month)

    try:
        summary = _generate_summary(config, report_month)
    except Exception as exc:
        log.error("Failed to gather report data: %s", exc)
        return False

    report_dir = config.paths.base_dir / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)

    html_file = report_dir / f"pipeline_report_{report_month}.html"
    csv_file = report_dir / f"pipeline_report_{report_month}.csv"

    _write_html_report(summary, html_file)
    _write_csv_report(summary, csv_file)

    # Upload to S3
    s3_upload_file(html_file, config, f"reports/{html_file.name}")
    s3_upload_file(csv_file, config, f"reports/{csv_file.name}")

    # Send notification
    send_slack(
        f"Monthly report for {report_month} generated. "
        f"Total rows: {summary.get('total_rows', 0):,}. "
        f"Files: {html_file.name}, {csv_file.name}",
        "INFO",
        config.slack,
    )

    log.info("Report generation complete for %s", report_month)
    return True


def main() -> None:
    """CLI entry point."""
    cfg = load_config()
    setup_logging(cfg.paths.log_dir, cfg.logging.log_level)

    month = sys.argv[1] if len(sys.argv) > 1 else None
    ok = generate_report(cfg, month)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
